
package Inventory;


import DatabaseConncection.DatabaseConnection;
import java.time.LocalDate;
import java.awt.Color;
import javax.swing.JOptionPane;


public class AddProduct extends javax.swing.JFrame {

    InventoryEmployee employee = new InventoryEmployee();
    DatabaseConnection DB = new DatabaseConnection();
    static String name , category;
    LocalDate pdate , edate;
    static double price;
    static int id , quantity , damages, shortage;
    int x,y;
    
    public AddProduct() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        emonth = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pyear = new javax.swing.JTextField();
        eday = new javax.swing.JTextField();
        pday = new javax.swing.JTextField();
        range = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        damage = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        damagIn = new javax.swing.JTextField();
        nameIn = new javax.swing.JTextField();
        priceIn = new javax.swing.JTextField();
        quantityIn = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        categoryIn = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        pmonth = new javax.swing.JTextField();
        eyear = new javax.swing.JTextField();
        shortIn = new javax.swing.JTextField();
        bar = new javax.swing.JPanel();
        close1 = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add");
        setUndecorated(true);

        addPanel.setBackground(new java.awt.Color(51, 51, 51));
        addPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Production_Date");

        emonth.setForeground(new java.awt.Color(204, 204, 204));
        emonth.setText("MM");
        emonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emonthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emonthFocusLost(evt);
            }
        });
        emonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emonthActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Expiry_Date");

        pyear.setForeground(new java.awt.Color(204, 204, 204));
        pyear.setText("YYYY");
        pyear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pyearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pyearFocusLost(evt);
            }
        });
        pyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyearActionPerformed(evt);
            }
        });

        eday.setForeground(new java.awt.Color(204, 204, 204));
        eday.setText("DD");
        eday.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edayFocusLost(evt);
            }
        });
        eday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edayActionPerformed(evt);
            }
        });

        pday.setForeground(new java.awt.Color(204, 204, 204));
        pday.setText("DD");
        pday.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pdayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pdayFocusLost(evt);
            }
        });
        pday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdayActionPerformed(evt);
            }
        });

        range.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        range.setForeground(new java.awt.Color(255, 255, 255));
        range.setText("Shortage");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");

        damage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        damage.setForeground(new java.awt.Color(255, 255, 255));
        damage.setText("Damages");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity");

        damagIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                damagInActionPerformed(evt);
            }
        });

        nameIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");

        categoryIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meat & Seafood", "Canned Goods", "Beverages", "Bread & Bakery", "Snacks & Candy", "Dairy & Eggs", "Frozen Foods", "Fruits & Vegetables", "Grains, Pasta & Sides", "Paper", "Cleaning Supplies", "Care Products" }));
        categoryIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryInActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Category");

        pmonth.setForeground(new java.awt.Color(204, 204, 204));
        pmonth.setText("MM");
        pmonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pmonthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pmonthFocusLost(evt);
            }
        });
        pmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmonthActionPerformed(evt);
            }
        });

        eyear.setForeground(new java.awt.Color(204, 204, 204));
        eyear.setText("YYYY");
        eyear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                eyearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                eyearFocusLost(evt);
            }
        });
        eyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyearActionPerformed(evt);
            }
        });

        shortIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortInActionPerformed(evt);
            }
        });

        bar.setBackground(new java.awt.Color(51, 51, 51));
        bar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });

        close1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 20)); // NOI18N
        close1.setForeground(new java.awt.Color(255, 255, 255));
        close1.setText("      X");
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
        });

        subTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subTitle.setForeground(new java.awt.Color(255, 255, 255));
        subTitle.setText("  Add Product");

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addComponent(subTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(close1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addComponent(subTitle))
        );

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(damage)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)))
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(priceIn, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(damagIn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(range))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quantityIn, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                    .addComponent(shortIn)))
                            .addComponent(save)))
                    .addComponent(nameIn))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancel)
                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(addPanelLayout.createSequentialGroup()
                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(eday)
                                .addComponent(pday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pmonth)
                                .addComponent(emonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pyear)
                                .addComponent(eyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(addPanelLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(categoryIn, 0, 1, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(priceIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(damage)
                                    .addComponent(damagIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(quantityIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(range)
                                    .addComponent(shortIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(categoryIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(pday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(eday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addPanelLayout.createSequentialGroup()
                                    .addComponent(pmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                                    .addComponent(pyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(eyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(cancel))
                .addContainerGap())
        );

        jLabel3.getAccessibleContext().setAccessibleName("");
        jLabel4.getAccessibleContext().setAccessibleName("");
        jLabel5.getAccessibleContext().setAccessibleName("");
        jLabel6.getAccessibleContext().setAccessibleName("");
        jLabel1.getAccessibleContext().setAccessibleName("");
        jLabel2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add(){
        try{
            getDataFromUser();
            int r = employee.addproduct(name, category, pdate, edate, price, quantity, damages,shortage);
            if(r==1)
                JOptionPane.showMessageDialog(null, "Product added!", "Success", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(null, "Invalid Input", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Input", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void nameInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInActionPerformed
        
    }//GEN-LAST:event_nameInActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        add();
        Inventory.model.setRowCount(0);
        Inventory.displayAllProducts();
    }//GEN-LAST:event_saveActionPerformed

    private void categoryInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryInActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void pmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmonthActionPerformed
        
    }//GEN-LAST:event_pmonthActionPerformed

    private void pmonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pmonthFocusLost
        focusLost(pmonth,"MM");
    }//GEN-LAST:event_pmonthFocusLost

    private void pmonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pmonthFocusGained
        focusGained(pmonth,"MM");
    }//GEN-LAST:event_pmonthFocusGained

    private void emonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emonthFocusGained
       focusGained(emonth, "MM");
    }//GEN-LAST:event_emonthFocusGained

    private void emonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emonthFocusLost
        focusLost(emonth, "MM");
    }//GEN-LAST:event_emonthFocusLost

    private void emonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emonthActionPerformed

    private void eyearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eyearFocusGained
        focusGained(eyear, "YYYY");
    }//GEN-LAST:event_eyearFocusGained

    private void eyearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eyearFocusLost
        focusLost(eyear, "YYYY");
    }//GEN-LAST:event_eyearFocusLost

    private void eyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eyearActionPerformed

    private void pyearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pyearFocusGained
        focusGained(pyear, "YYYY");
    }//GEN-LAST:event_pyearFocusGained

    private void pyearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pyearFocusLost
        focusLost(pyear, "YYYY");
    }//GEN-LAST:event_pyearFocusLost

    private void pyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pyearActionPerformed

    private void edayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edayFocusGained
        focusGained(eday, "DD");
    }//GEN-LAST:event_edayFocusGained

    private void edayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edayFocusLost
        focusLost(eday, "DD");
    }//GEN-LAST:event_edayFocusLost

    private void edayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edayActionPerformed

    private void pdayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pdayFocusGained
        focusGained(pday, "DD");
    }//GEN-LAST:event_pdayFocusGained

    private void pdayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pdayFocusLost
        focusLost(pday, "DD");
    }//GEN-LAST:event_pdayFocusLost

    private void pdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdayActionPerformed

    private void shortInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shortInActionPerformed

    private void damagInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_damagInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_damagInActionPerformed

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_barMouseDragged

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked
         this.dispose();
    }//GEN-LAST:event_close1MouseClicked
    private void getDataFromUser(){
        name = nameIn.getText();
        category = (String)categoryIn.getSelectedItem();
        pdate = LocalDate.parse(pyear.getText()+'-'+correctDate(pmonth.getText())+'-'+correctDate(pday.getText()));
        edate = LocalDate.parse(eyear.getText()+'-'+correctDate(emonth.getText())+'-'+correctDate(eday.getText()));
        price = Double.parseDouble(priceIn.getText());
        quantity = Integer.parseInt(quantityIn.getText());
        damages = Integer.parseInt(damagIn.getText());
        shortage = Integer.parseInt(shortIn.getText());
        if(quantity<=shortage)
            JOptionPane.showMessageDialog(null,"The quantity is below the specified range("+shortage+")","Warning", JOptionPane.WARNING_MESSAGE);
    }
    private void focusGained(javax.swing.JTextField textField,String string){
        if(textField.getText().equals(string)){
            textField.setText("");
            textField.setForeground(Color.BLACK);
        }
    }
    private void focusLost(javax.swing.JTextField textField,String string){
        if(textField.getText().equals("")){
            textField.setText(string);
            textField.setForeground(Color.lightGray);
        }
    }
    private String correctDate(String date){
        if(date.length()==1){
            date = "0"+date.charAt(0);
            return date;
        }
        else
            return date;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPanel;
    private javax.swing.JPanel bar;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> categoryIn;
    private javax.swing.JLabel close1;
    private javax.swing.JTextField damagIn;
    private javax.swing.JLabel damage;
    private javax.swing.JTextField eday;
    private javax.swing.JTextField emonth;
    private javax.swing.JTextField eyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameIn;
    private javax.swing.JTextField pday;
    private javax.swing.JTextField pmonth;
    private javax.swing.JTextField priceIn;
    private javax.swing.JTextField pyear;
    private javax.swing.JTextField quantityIn;
    private javax.swing.JLabel range;
    private javax.swing.JButton save;
    private javax.swing.JTextField shortIn;
    private javax.swing.JLabel subTitle;
    // End of variables declaration//GEN-END:variables
}
