
package Users;

import javax.swing.JOptionPane;

public class UpdateProfile extends javax.swing.JFrame {

        int x, y;
        User user = new User();

        public UpdateProfile() {
                initComponents();
                name.setText(user.getUsername());
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                profilePanel = new javax.swing.JPanel();
                bar = new javax.swing.JPanel();
                close1 = new javax.swing.JLabel();
                subTitle = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                name = new javax.swing.JTextField();
                pass = new javax.swing.JPasswordField();
                update = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);
                setResizable(false);

                profilePanel.setBackground(new java.awt.Color(51, 51, 51));

                bar.setBackground(new java.awt.Color(51, 51, 51));
                bar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseDragged(java.awt.event.MouseEvent evt) {
                                barMouseDragged(evt);
                        }
                });
                bar.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                barMousePressed(evt);
                        }
                });

                close1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 20)); // NOI18N
                close1.setForeground(new java.awt.Color(255, 255, 255));
                close1.setText("      X");
                close1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                close1MouseClicked(evt);
                        }
                });

                subTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                subTitle.setForeground(new java.awt.Color(255, 255, 255));
                subTitle.setText("  Update Profile");

                javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
                bar.setLayout(barLayout);
                barLayout.setHorizontalGroup(
                                barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout
                                                                .createSequentialGroup()
                                                                .addComponent(subTitle)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(close1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                50,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
                barLayout.setVerticalGroup(
                                barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(barLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(close1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                25, Short.MAX_VALUE)
                                                                .addComponent(subTitle)));

                jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Username");

                jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Password");

                pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

                update.setText("Update");
                update.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                updateActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
                profilePanel.setLayout(profilePanelLayout);
                profilePanelLayout.setHorizontalGroup(
                                profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                .addGroup(profilePanelLayout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(profilePanelLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                profilePanelLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jLabel1)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                profilePanelLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addGap(14, 14, 14)))
                                                                .addGroup(profilePanelLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(update)
                                                                                .addGroup(profilePanelLayout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                .addComponent(pass)
                                                                                                .addComponent(name,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                138,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(24, Short.MAX_VALUE)));
                profilePanelLayout.setVerticalGroup(
                                profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(profilePanelLayout.createSequentialGroup()
                                                                .addComponent(bar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                33,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(profilePanelLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(name,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(32, 32, 32)
                                                                .addGroup(profilePanelLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(pass,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(28, 28, 28)
                                                                .addComponent(update)
                                                                .addGap(23, 23, 23)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(profilePanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(profilePanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void close1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_close1MouseClicked
                this.dispose();
        }// GEN-LAST:event_close1MouseClicked

        private void barMouseDragged(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_barMouseDragged
                int xx = evt.getXOnScreen();
                int yy = evt.getYOnScreen();
                this.setLocation(xx - x, yy - y);
        }// GEN-LAST:event_barMouseDragged

        private void barMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_barMousePressed
                x = evt.getX();
                y = evt.getY();
        }// GEN-LAST:event_barMousePressed

        private void updateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateActionPerformed
                int r;
                if (pass.getText().isEmpty())
                        r = user.updateProfileUserName(name.getText());//
                else if (name.getText().isEmpty())
                        r = user.updateProfilePassword(pass.getText());//
                else
                        r = user.updateProfile(name.getText(), pass.getText());//
                if (r == 1) {
                        JOptionPane.showMessageDialog(null, "Profile updated successfuly!");
                        this.dispose();
                } else
                        JOptionPane.showMessageDialog(null, "Invalid input", "Error", JOptionPane.ERROR_MESSAGE);
        }// GEN-LAST:event_updateActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new UpdateProfile().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel bar;
        private javax.swing.JLabel close1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JTextField name;
        private javax.swing.JPasswordField pass;
        private javax.swing.JPanel profilePanel;
        private javax.swing.JLabel subTitle;
        private javax.swing.JButton update;
        // End of variables declaration//GEN-END:variables
}